apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneDeployment
metadata:
  name: openstack-edpm-ipam-reboot
  namespace: openstack
spec:
  nodeSets:
    - openstack-edpm-compute-1
  servicesOverride: 
  - reboot-os
  ansibleExtraVars: 
    edpm_reboot_strategy: force
  ansibleLimit: 
    - edpm-compute-1.sandbox-UUID-ocp4-cluster.svc.cluster.local