apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneDeployment
metadata:
  name: openstack-edpm-ipam-reboot-check
  namespace: openstack
spec:
  nodeSets:
    - openstack-edpm-compute-1
  servicesOverride: 
  - reboot-os