apiVersion: network.openstack.org/v1beta1
kind: NetConfig
metadata:
  name: openstacknetconfig
  namespace: openstack
spec:
  networks:
  - name: ctlplane
    dnsDomain: ctlplane.sandbox-UUID-ocp4-cluster.svc.cluster.local
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 172.22.0.120
        start: 172.22.0.100
      - end: 172.22.0.200
        start: 172.22.0.150
      cidr: 172.22.0.0/24
      gateway: 172.22.0.1
  - name: internalapi 
    dnsDomain: internalapi.sandbox-UUID-ocp4-cluster.svc.cluster.local
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 172.17.0.250
        start: 172.17.0.100
      excludeAddresses:
      - 172.17.0.10
      - 172.17.0.12
      cidr: 172.17.0.0/24
  - name: tenant
    dnsDomain: tenant.sandbox-UUID-ocp4-cluster.svc.cluster.local
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 172.19.0.250
        start: 172.19.0.100
      excludeAddresses:
      - 172.19.0.10
      - 172.19.0.12
      cidr: 172.19.0.0/24
  - name: storage
    dnsDomain: storage.sandbox-UUID-ocp4-cluster.svc.cluster.local
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 172.18.0.250
        start: 172.18.0.100
      excludeAddresses:
      - 172.18.0.10
      - 172.18.0.12
      cidr: 172.18.0.0/24
  - name: external
    dnsDomain: external.sandbox-UUID-ocp4-cluster.svc.cluster.local
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 10.0.2.250
        start: 10.0.2.2
      excludeAddresses:
      - 10.0.2.1
      cidr: 10.0.2.0/24